question_data = [
    {"response_code": 0, "results": [{"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
                                      "question": "Which animated movie was first to feature a celebrity as a voice actor?",
                                      "correct_answer": "Aladdin",
                                      "incorrect_answers": ["Toy Story", "James and the Giant Peach",
                                                            "The Hunchback of Notre Dame"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "hard",
                                      "question": "What is the name of the virus that infected New York in Tom Clancy&#039;s The Division?",
                                      "correct_answer": "Dollar Flu",
                                      "incorrect_answers": ["Ebola", "Red Poison", "Smallpox"]},
                                     {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
                                      "question": "Which actress danced the twist with John Travolta in &#039;Pulp Fiction&#039;?",
                                      "correct_answer": "Uma Thurman",
                                      "incorrect_answers": ["Kathy Griffin", "Pam Grier", "Bridget Fonda"]},
                                     {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
                                      "question": "What is the orange and white bot&#039;s name in &quot;Star Wars: The Force Awakens&quot;?",
                                      "correct_answer": "BB-8", "incorrect_answers": ["BB-3", "AA-A", "R2-D2"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Which of the following car manufacturers had a war named after it?",
                                      "correct_answer": "Toyota", "incorrect_answers": ["Honda", "Ford", "Volkswagen"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                      "question": "In 2015, David Hasselhof released a single called...",
                                      "correct_answer": "True Survivor",
                                      "incorrect_answers": ["True Fighter", "Real Kung-Fury", "Real Warrior"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "Where was the Sniper character in Team Fortress 2 born?",
                                      "correct_answer": "New Zealand",
                                      "incorrect_answers": ["South Africa", "Antarctica", "Australia"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "In the anime series &quot;Full Metal Alchemist&quot;, what do Alchemists consider the greatest taboo?",
                                      "correct_answer": "Human Transmutation ",
                                      "incorrect_answers": ["Transmuting Lead Into Gold", "Using Alchemy For Crime ",
                                                            "Preforming Without A Permit"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                      "question": "What&#039;s the most common time signature for rock songs?",
                                      "correct_answer": "4\/4", "incorrect_answers": ["1\/2", "8\/12", "2\/4"]},
                                     {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of these Roman gods doesn&#039;t have a counterpart in Greek mythology?",
                                      "correct_answer": "Janus", "incorrect_answers": ["Vulcan", "Juno", "Mars"]},
                                     {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
                                      "question": "In Game of Thrones, what continent lies across the Narrow Sea from Westeros?",
                                      "correct_answer": "Essos",
                                      "incorrect_answers": ["Easteros", "Westereast", "Esuntos"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                      "question": "What is the name of the main character from the music video of &quot;Shelter&quot; by Porter Robinson and A-1 Studios?",
                                      "correct_answer": "Rin", "incorrect_answers": ["Rem", "Ren", "Ram"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "Who turns out to be the true victor in the Battle of Armageddon in Mortal Kombat?",
                                      "correct_answer": "Shao Kahn",
                                      "incorrect_answers": ["Liu Kang", "Shang Tsung", "Raiden"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "Satella in &quot;Re:Zero&quot; is the witch of what?",
                                      "correct_answer": "Envy", "incorrect_answers": ["Pride", "Sloth", "Wrath"]},
                                     {"category": "Entertainment: Television", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "Alan Reed is known for providing the voice of which character?",
                                      "correct_answer": "Fred Flintstone",
                                      "incorrect_answers": ["Bugs Bunny", "Fangface", "G.I. Joe"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "In the &quot;Portal&quot; series, who was Cave Johnson&#039;s personal assistant?",
                                      "correct_answer": "Caroline",
                                      "incorrect_answers": ["Heather", "Melissa", "Jane"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "What is the main character&#039;s name in &quot;Braid&quot;?",
                                      "correct_answer": "Tim", "incorrect_answers": ["Boregard", "James", "Jackson"]},
                                     {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
                                      "question": "In &quot;Rick And Morty&quot;, who shot &quot;Mr. Poopybutthole&quot; in the episode &quot;Total Rickall&quot;?",
                                      "correct_answer": "Beth", "incorrect_answers": ["Rick", "Jerry", "Morty"]},
                                     {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
                                      "question": "An organism described as &quot;heliotropic&quot; has a tendancy to move towards which of these things?",
                                      "correct_answer": "Light", "incorrect_answers": ["Water", "Trees", "Pollen"]},
                                     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
                                      "question": "Earth is located in which galaxy?",
                                      "correct_answer": "The Milky Way Galaxy",
                                      "incorrect_answers": ["The Mars Galaxy", "The Galaxy Note", "The Black Hole"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                      "question": "Which artist curated the official soundtrack for &quot;The Hunger Games: Mockingjay - Part 1&quot;?",
                                      "correct_answer": "Lorde",
                                      "incorrect_answers": ["Kanye West", "Tove Lo", "Charli XCX"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "Which of the following weapons in &quot;Counter-Strike: Global Offensive&quot; does not have a right-click function?",
                                      "correct_answer": "XM1014",
                                      "incorrect_answers": ["SG553", "R8 Revolver", "USP-S"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "In &quot;Yo! Noid 2,&quot; The Noid can perform what special move?",
                                      "correct_answer": "Dab",
                                      "incorrect_answers": ["Pizza Throw", "Dodge Roll", "Spin Dash"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                                      "question": "Lenovo acquired IBM&#039;s personal computer division, including the ThinkPad line of laptops and tablets, in what year?",
                                      "correct_answer": "2005", "incorrect_answers": ["1999", "2002", "2008"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "In Splatoon 2, who are the members of Off The Hook?",
                                      "correct_answer": "Pearl &amp; Marina",
                                      "incorrect_answers": ["Callie &amp; Marie", "Diamond &amp; Aquamarina",
                                                            "DJ Octavio &amp; Crusty Sean"]}]}
]
